<?php

namespace Vendi\Theme\Component;

use Vendi\Theme\BaseComponent;

class LinkRow extends BaseComponent
{
    public function __construct()
    {
        parent::__construct(
            'component-link-row',
            _supportsBackgroundVideo: false,
            includeRegionWrap: false,
            includeContentWrap: false,
        );
    }

    public function setComponentCssProperties(): void
    {
        parent::setComponentCssProperties(); // TODO: Change the autogenerated stub
        if ($image_color = $this->getSubField('image_color')) {
            $this->componentStyles->addCssProperty('--local-image-color', $image_color);
        }

        if ($button_color = $this->getSubField('button_color')) {
            $this->componentStyles->addCssProperty('--local-button-color', $button_color);
        }
    }

    protected function abortRender(): bool
    {
        if ( ! get_sub_field('heading') && ! get_sub_field('copy')) {
            return true;
        }

        /*
<h3 class="heading"><?php esc_html_e(get_sub_field('heading')); ?></h3>
            <div class="copy"><?php echo wp_kses_post(get_sub_field('copy')); ?></div>
         */

        return parent::abortRender(); // TODO: Change the autogenerated stub
    }


}
