<?php

namespace Vendi\Theme\Component;

use Vendi\Theme\BaseComponentWithPrimaryHeading;

class ActionCards extends BaseComponentWithPrimaryHeading
{
    protected function abortRender(): bool
    {
        if ( ! $this->getCards()) {
            return true;
        }

        return parent::abortRender();
    }

    public function __construct()
    {
        parent::__construct('component-action-cards');
    }

    private function getCards(): array
    {
        return $this->getSubField('cards');
    }

    protected function initComponent(): void
    {
        parent::initComponent(); // TODO: Change the autogenerated stub
        if ($cards = $this->getCards()) {
            $this->addRootClass('card-count-' . count($cards));
        }
    }
}
