<?php

namespace Vendi\Theme\Component;

use Vendi\Theme\BaseComponentWithPrimaryHeading;
use Vendi\Theme\ComponentInterfaces\CallsToActionAwareInterface;
use Vendi\Theme\ComponentInterfaces\ColorSchemeAwareInterface;
use Vendi\Theme\ComponentInterfaces\ImageSettingsAwareInterface;
use Vendi\Theme\Traits\ColorSchemeTrait;
use Vendi\Theme\Traits\CommonCallsToActionTrait;
use Vendi\Theme\Traits\ImageSettingsTrait;

class FloatingCallout extends BaseComponentWithPrimaryHeading implements ColorSchemeAwareInterface, CallsToActionAwareInterface, ImageSettingsAwareInterface
{
    use ImageSettingsTrait;
    use ColorSchemeTrait;
    use CommonCallsToActionTrait;

    public function __construct()
    {
        parent::__construct('component-floating-callout');
    }
    public function setComponentCssProperties(): void
    {
        parent::setComponentCssProperties(); // TODO: Change the autogenerated stub

        $this->addRootClass('sub-component-basic-copy');
        $image_settings = $this->getSubField('image_settings');
        if ($image_settings) {
            $this->addRootClass('image-settings-' . $image_settings);
        }

        if (($image = $this->getSubField('image')) && $src = (bis_get_attachment_image_src($image['ID'], 'full')['src'] ?? null)) {
            $this->addRootClass('has-image');
            $this->componentStyles->addCssPropertyUrl('callout-image-background-src', $src);

            [$loginBackgroundPositionX, $loginBackgroundPositionY] = sanitize_focal_point(get_post_meta($image['ID'], 'focal_point', true));
            $loginBackgroundPositionX *= 100;
            $loginBackgroundPositionY *= 100;
            $this->componentStyles->addCssProperty('callout-image-background-position', "{$loginBackgroundPositionX}% {$loginBackgroundPositionY}%");

            // TODO
            $this->componentStyles->addCssProperty('callout-image-background-size', 'cover');
        }

        if ($column_widths = $this->getSubField('column_widths')) {
            if ('1fr-2fr' === $column_widths && 'background-shield' === $image_settings) {
                $column_widths = '30rem-1fr';
            }
            $column_widths = implode(' ', explode('-', $column_widths));
            $this->componentStyles->addCssProperty('callout-column-width', $column_widths);
        }
    }
}
