<?php

namespace Vendi\Theme\Component;

use Vendi\Theme\BaseComponentWithPrimaryHeading;

abstract class ImageGalleryBase extends BaseComponentWithPrimaryHeading
{
    public function __construct()
    {
        parent::__construct('component-image-gallery');
    }

    public function getImagesAcross(): int
    {
        return $this->getSubFieldRangeInt('images_across', min: 1, max: 8, default: 4);
    }

    public function getImageFitting(): string
    {
        $value = $this->getSubField('image_fitting');

        return vendi_constrain_item_to_list($value, ['contain', 'cover', 'none', 'fill', 'scale-down'], 'scale-down');
    }

    public function getImageCaptions(): string
    {
        $value = $this->getSubField('image_captions');

        return vendi_constrain_item_to_list($value, ['none', 'caption', 'title', 'title-and-caption'], 'none');
    }

    public function getRootClasses(): array
    {
        $ret = parent::getRootClasses(); // TODO: Change the autogenerated stub

        $ret[] = 'grid-column-count-' . $this->getImagesAcross();
        $ret[] = 'image-fitting-' . $this->getImageFitting();
        $ret[] = 'image-captions-' . $this->getImageCaptions();

        return $ret;
    }

    public function setComponentCssProperties(): void
    {
        $this->componentStyles->addStyle('--local-text-color', $this->getSubField('text_color'));

        if ($gap = $this->getSubField('image_gap')) {
            $this->componentStyles->addStyle('--local-gap', $gap . 'rem');
        }
    }
}
