<?php

const VENDI_CUSTOM_THEME_COMPONENT_FIELD_NAME = 'content_components';

const VENDI_CUSTOM_THEME_PARTS_ROOT = '/vendi-theme-parts';

const VENDI_CUSTOM_THEME_FEATURE_FOLDER_NAME   = VENDI_CUSTOM_THEME_PARTS_ROOT . '/features';
const VENDI_CUSTOM_THEME_COMPONENT_FOLDER_NAME = VENDI_CUSTOM_THEME_PARTS_ROOT . '/components';
const VENDI_CUSTOM_THEME_TEMPLATE_FOLDER_NAME  = VENDI_CUSTOM_THEME_PARTS_ROOT . '/templates';

const VENDI_LIBRARY_ASSET_HANDLE_SLICK_CSS       = 'slick-css';
const VENDI_LIBRARY_ASSET_HANDLE_SLICK_THEME_CSS = 'slick-theme-css';
const VENDI_LIBRARY_ASSET_HANDLE_SLICK_JS        = 'slick-js';

const VENDI_LIBRARY_ASSET_HANDLE_BAGUETTE_BOX_CSS = 'baguette-box-css';
const VENDI_LIBRARY_ASSET_HANDLE_BAGUETTE_BOX_JS  = 'baguette-box-js';
